apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "demo.fullname" . }}-db
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.store }}
  target:
    name: {{ include "demo.fullname" . }}-db
  data:
    - secretKey: DB_URL
      remoteRef:
        key: {{ .Values.externalSecrets.dbUrlKey }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "demo.fullname" . }}-pull
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.store }}
  target:
    name: ghcr-pull
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: {{ .Values.externalSecrets.pullSecretKey }}
